const mongoose = require("mongoose");

const configDataSchema = new mongoose.Schema({
    // PORT: { type: Number },
    PRODUCTION: { type: Boolean },
    // MONGODB_URL: { type: String },

    JWT_SECRET: { type: String },
    PAYPAL_CLIENT_ID: { type: String },
    PAYPAL_CLIENT_SECRET: { type: String },
    EMAIL: { type: String },
    PASSWORD: { type: String },
    CCAVENUE_MERCHANT_ID: { type: Number },
    CCAVENUE_ACCESS_CODE: { type: String },
    CCAVENUE_WORKING_KEY: { type: String },
    RAZORPAY_KEY_ID: { type: String },
    RAZORPAY_KEY_SECRET: { type: String },
    SERVER_URL: { type: String },
    REACT_APP_URL: { type: String },
    B2B_WEB_URL: { type: String },
    ADMIN_WEB_URL: { type: String },
    BURJ_KHALIFA_USERNAME: { type: String },
    BURJ_KHALIFA_PASSWORD: { type: String },
    INSURANCE_SERVER_URL: { type: String },
    WHATSAPP_SERVER_URL: { type: String },
    CYGNET_USERNAME: { type: String },
    CYGNET_PASSWORD: { type: String },
    CYGNET_TENANT: { type: Number },
    CYGNET_AGENCY: { type: Number },
    HOTEL_BEDS_URL: { type: String },
    HOTEL_BEDS_API_KEY: { type: String },
    HOTEL_BEDS_SECRET: { type: String },
    FLIGHT_SERVER_URL: { type: String },
    COMPANY_NAME: { type: String, required: [true, "Company name is required"] },
    COMPANY_REGISTRATION_NAME: { type: String },
    COMPANY_LOGO: { type: String, required: true },
    FAV_IMAGE:  { type: String, required: true },
    COMPANY_SHORT_NAME: { type: String, required: true },
    NODE_ENV: { type: String },
    REDIS_REQUIRED: { type: Boolean },
    LOGIN_AGENTCODE_REQUIRED: { type: Boolean },
    NOTIFICATION_KEY: { type: String },
    OTTILA_BASE_URL: { type: String },
    OTTILA_USERNAME: { type: String },
    OTTILA_PASSWORD: { type: String },
    DATA_FEED: { type: Boolean },
    CHECK:{type : Number},
    NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: { type: String },
    CLOUDINARY_API_KEY: { type: Number },
    CLOUDINARY_API_SECRET: { type: String },
    CLOUDINARY_FOLDER: { type: String },
    GOOGLE_CLIENT_ID: { type: String },
    GOOGLE_CLIENT_SECRET: { type: String },
    NEXTAUTH_SECRET: { type: String },
    NEXTAUTH_URL: { type: String },
    NEXT_PUBLIC_GOOGLE_ANALYTIC_ID: { type: String },
    NEXT_PUBLIC_TABBY_PUBLIC_KEY: { type: String },
    NEXT_PUBLIC_TABBY_MERCHANT_CODE: { type: String },
    NEXT_PUBLIC_TOURS_URL: { type: String },
    NEXT_PUBLIC_SERVER_URL: { type: String },
    NEXT_PUBLIC_CLIENT_URL: { type: String },
    NEXT_PUBLIC_CDN_URL: { type: String },
    NEXT_PUBLIC_TITLE_NAME: { type: String },
    NEXT_PUBLIC_TITLE_SHORT_NAME: { type: String },
    NEXT_PUBLIC_TITLE_SHORT_CODE: { type: String },
    NEXT_PUBLIC_COMPANY_LOGO: { type: String },
    NEXT_PUBLIC_COMPANY_FAVICON: { type: String },
    NEXT_PUBLIC_BANNER_IMAGE: { type: String },
    NEXT_PUBLIC_BANNER_VIDEO: { type: String },
    NEXT_PUBLIC_BANNER_VIDEO_MOBILE: { type: String },
    NEXT_PUBLIC_BANNER_IMAGE_MOBILE: { type: String },
    NEXT_PUBLIC_MOBILE_APP_iMAGE: { type: String },
    NEXT_PUBLIC_PLAYSTORE_URL: { type: String },
    NEXT_PUBLIC_COMPANYADDRESS1: { type: String },
    NEXT_PUBLIC_COMPANYADDRESS2 : { type: String },
});

const ConfigData = mongoose.model("ConfigData", configDataSchema);

module.exports = ConfigData;
